FROM python:3.11-slim

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir grpcio grpcio-tools protobuf
RUN mkdir -p /data/oplog

# Generate Python stubs
RUN python -m grpc_tools.protoc -I./proto \
    --python_out=./master --grpc_python_out=./master ./proto/master.proto

# Will fail to start until you implement server.py in Phase 1
CMD ["python", "master/server.py"]